### ISSUE TITLE
BUG: Build faliure with `ERROR: Executables created by c compiler ccache cc are not runnable`

### ISSUE THREAD

**Issue by bbhtt** [numpy/numpy#24763]
### Describe the issue:

Building 1.26.0 in a flatpak fails with the following error:

```shell
Building module python3-numpy in /home/wirt/Git/github/flatpaks/io.github.hydrusnetwork.hydrus/.flatpak-builder/build/python3-numpy-2
========================================================================
Running: pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}" --prefix=${FLATPAK_DEST} "numpy>=1.16.0" --no-build-isolation
Using pip 23.1.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)
Looking in links: file:///run/build/python3-numpy
Processing ./numpy-1.26.0.tar.gz
  Running command Preparing metadata (pyproject.toml)
  + /usr/bin/python3 /tmp/pip-install-yhs5sskh/numpy_acb07d7a50cf4965aec2d8a61298c740/vendored-meson/meson/meson.py setup /tmp/pip-install-yhs5sskh/numpy_acb07d7a50cf4965aec2d8a61298c740 /tmp/pip-install-yhs5sskh/numpy_acb07d7a50cf4965aec2d8a61298c740/.mesonpy-p53js80g/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-yhs5sskh/numpy_acb07d7a50cf4965aec2d8a61298c740/.mesonpy-p53js80g/build/meson-python-native-file.ini
  The Meson build system
  Version: 1.2.99
  Source dir: /tmp/pip-install-yhs5sskh/numpy_acb07d7a50cf4965aec2d8a61298c740
  Build dir: /tmp/pip-install-yhs5sskh/numpy_acb07d7a50cf4965aec2d8a61298c740/.mesonpy-p53js80g/build
  Build type: native build
  Project name: NumPy
  Project version: 1.26.0

  ../../meson.build:1:0: ERROR: Executables created by c compiler ccache cc are not runnable.

  A full log can be found at /tmp/pip-install-yhs5sskh/numpy_acb07d7a50cf4965aec2d8a61298c740/.mesonpy-p53js80g/build/meson-logs/meson-log.txt
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /usr/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpb807fdo3
  cwd: /tmp/pip-install-yhs5sskh/numpy_acb07d7a50cf4965aec2d8a61298c740
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: module python3-numpy: Child process exited with code 1
```

### Reproduce the code example:

1. Run `flatpak-builder build --force-clean test.yaml`

```yaml
app-id: com.example.test
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk

modules:

  - name: lapack
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DBUILD_SHARED_LIBS=ON
      - -DBUILD_TESTING=OFF
      - -DLAPACKE=ON
      - -DCBLAS=ON
    sources:
      - type: git
        url: https://github.com/Reference-LAPACK/lapack.git
        tag: v3.11.0
        commit: 7866626840f5d5e7e27f027a55182da8b3303872

  - name: openblas
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -DBUILD_SHARED_LIBS=ON
      - -DBUILD_TESTING=OFF
      - -DNO_AFFINITY=ON
      - -DUSE_OPENMP=1
      - -DNO_WARMUP=1
      - -DCORE=CORE2
      - -DNUM_THREADS=64
      - -DDYNAMIC_ARCH=ON
    sources:
      - type: archive
        url: https://github.com/xianyi/OpenBLAS/archive/v0.3.24.tar.gz
        sha256: ceadc5065da97bd92404cac7254da66cc6eb192679cf1002098688978d4d5132

  - name: python3-tomli
    buildsystem: simple
    build-commands:
      - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}"
        --prefix=${FLATPAK_DEST} "tomli" --no-build-isolation
    sources:
      - type: file
        url: https://files.pythonhosted.org/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl
        sha256: 939de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc

  - name: python3-pyproject-metadata
    buildsystem: simple
    build-commands:
      - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}"
        --prefix=${FLATPAK_DEST} "pyproject-metadata" --no-build-isolation
    sources:
      - type: file
        url: https://files.pythonhosted.org/packages/ab/c3/57f0601a2d4fe15de7a553c00adbc901425661bf048f2a22dfc500caf121/packaging-23.1-py3-none-any.whl
        sha256: 994793af429502c4ea2ebf6bf664629d07c1a9fe974af92966e4b8d2df7edc61
      - type: file
        url: https://files.pythonhosted.org/packages/c4/cb/4678dfd70cd2f2d8969e571cdc1bb1e9293c698f8d1cf428fadcf48d6e9f/pyproject_metadata-0.7.1-py3-none-any.whl
        sha256: 28691fbb36266a819ec56c9fa1ecaf36f879d6944dfde5411e87fc4ff793aa60

  - name: python3-numpy
    buildsystem: simple
    build-options:
      env:
        ATLAS: None
        BLAS: /app/lib
        LAPACK: /app/lib
        LDFLAGS: -shared
    build-commands:
      - pip3 install --verbose --exists-action=i --no-index --find-links="file://${PWD}"
        --prefix=${FLATPAK_DEST} "numpy" --no-build-isolation
    sources:
      - type: file
        url: https://files.pythonhosted.org/packages/55/b3/b13bce39ba82b7398c06d10446f5ffd5c07db39b09bd37370dc720c7951c/numpy-1.26.0.tar.gz
        sha256: f93fc78fe8bf15afe2b8d6b6499f1c73953169fad1e9a8dd086cdff3190e7fdf
```

### Error message:

```shell
See above
```

### Runtime information:

```
python --version
Python 3.10.13
```

### Context for the issue:

N/A
