### ISSUE TITLE
BUG: wrong errors "divide by zero encountered in matmul" on MacOS

### ISSUE THREAD

**Issue by malciin** [numpy/numpy#28687]
### Describe the issue:

I guess its self explanatory. Following code:

`np.identity(n=784) @ np.identity(n=784)`

produces many wrong runtime warnings.

For small matrices is works as expected, for eg. `np.ones(shape=(1, 1)) @ np.ones(shape=(1, 784))` doesn't produce warning.

### Reproduce the code example:

```python
import numpy as np
np.identity(n=784) @ np.identity(n=784)

# same result for
import numpy as np
np.ones(shape=(1, 2)) @ np.ones(shape=(2, 784))
```

### Error message:

```shell
../test.py:3: RuntimeWarning: divide by zero encountered in matmul
  np.identity(n=784) @ np.identity(n=784)
../test.py:3: RuntimeWarning: overflow encountered in matmul
  np.identity(n=784) @ np.identity(n=784)
../test.py:3: RuntimeWarning: invalid value encountered in matmul
  np.identity(n=784) @ np.identity(n=784)
```

### Python and NumPy Versions:

2.2.4
3.13.2 | packaged by Anaconda, Inc. | (main, Feb  6 2025, 12:55:35) [Clang 14.0.6 ]

**Comment by tylerjereddy** [comment]
FWIW, I don't see the issue on latest `main` on MacOS with accelerate backend nor latest `main` on x86_64 Linux with OpenBLAS backend:

```diff
--- a/numpy/linalg/tests/test_linalg.py
+++ b/numpy/linalg/tests/test_linalg.py
@@ -2406,3 +2406,12 @@ def test_vector_norm_empty():
         assert_equal(np.linalg.vector_norm(x, ord=1), 0)
         assert_equal(np.linalg.vector_norm(x, ord=2), 0)
         assert_equal(np.linalg.vector_norm(x, ord=np.inf), 0)
+
+
+
+@pytest.mark.parametrize("arr1, arr2", [
+    (np.identity(n=784), np.identity(n=784)),
+    (np.identity(n=14), np.identity(n=14)),
+])
+def test_gh_28687(arr1, arr2):
+    arr1 @ arr2
```

Incantation: `spin test -t numpy/linalg/tests/test_linalg.py::test_gh_28687 -- -s`

Maybe someone with a `conda` setup on Mac will reproduce more easily if this is just for a standard `conda` install. Sharing the contents of `np.show_config()` may also help.

**Comment by malciin** [comment]
Result of `np.show_config()` run in miniconda env

```yaml
Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.12
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/0j/bwqcs4y508s2n4ck4dhf3rpc0000gn/T/build-env-310vy4bc/bin/python
  version: '3.13'
SIMD Extensions:
  baseline:
  - NEON
  - NEON_FP16
  - NEON_VFPV4
  - ASIMD
  found:
  - ASIMDHP
  not found:
  - ASIMDFHM
```

But I believe its not related to conda. I can also reproduce it on default python3 installation on my mac:

![Image](https://github.com/user-attachments/assets/15580c2c-229a-442d-b163-64efde7d0396)

Result of `np.show_config()` for default python3 instalation:

```json
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "system",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "system",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/private/var/folders/4d/0gnh84wj53j7wyk695q0tc_80000gn/T/build-env-kq4kuj35/bin/python",
    "version": "3.9"
  },
  "SIMD Extensions": {
    "baseline": [
      "NEON",
      "NEON_FP16",
      "NEON_VFPV4",
      "ASIMD"
    ],
    "found": [
      "ASIMDHP"
    ],
    "not found": [
      "ASIMDFHM"
    ]
  }
}
```
