### ISSUE TITLE
3.14 wheels

### ISSUE THREAD

**Issue by kasium** [numpy/numpy#29062]
Hi,

python 3.14 beta phase started and I can see a couple of PRs about 3.14.
Do you have already a target version when you plan to publish 3.14 wheels?

Thanks a lot!

**Comment by mattip** [comment]
Copying from a message by @ngoldbaum on the [scientific python discord maintainers channel](https://discord.com/channels/786703927705862175/1020054153902428171)
> As of this weekend NumPy has 3.14 and 3.14t nightlies on the [nightly wheel repository](https://anaconda.org/scientific-python-nightly-wheels/numpy). The Python 3.14 ABI isn’t stable yet so don’t release 3.14 wheels to pypi quite yet, but hopefully that helps unblock getting any issues on 3.14 or 3.14t resolved for packages you maintain so you can set up nightlies as well with a lot of time before the 3.14 release in October.

**Comment by Avasam** [comment]
For use with uv:
```toml
[project]
dependencies = [
  "numpy >=2.4.0.dev0", # Python 3.14 support
]
[tool.uv.sources]
numpy = { index = "scientific-python-nightly-wheels" }
[[tool.uv.index]]
name = "scientific-python-nightly-wheels"
url = "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple"
explicit = true
```
