### ISSUE TITLE
Trouble with round trip with rfft/irfft

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#8800]
Ran into a bug when trying to do the round trip with `rfft` and `irfft` from NumPy. The same error is not present with SciPy (however they also go about getting the results differently). Example code to reproduce the problem below.

<details>

```python
In [1]: import numpy

In [2]: import numpy as np

In [3]: import numpy.fft

In [4]: import numpy.fft as npfft

In [5]: import scipy

In [6]: import scipy as sp

In [7]: import scipy.fftpack

In [8]: import scipy.fftpack as spfft

In [9]: a = numpy.array([9.0, -9.0, 1.0, 3.0])

In [10]: b = numpy.array([-9.0, 1.0, 3.0])

In [11]: npfft.irfft(npfft.rfft(a))
Out[11]: array([ 9., -9.,  1.,  3.])

In [12]: npfft.irfft(npfft.rfft(b))
Out[12]: array([-8.,  3.])

In [13]: spfft.irfft(spfft.rfft(a))
Out[13]: array([ 9., -9.,  1.,  3.])

In [14]: spfft.irfft(spfft.rfft(b))
Out[14]: array([-9.,  1.,  3.])
```

</details>
<br>

Details about the environment ([creatable]( https://conda.io/docs/using/envs.html#use-environment-from-file ) with `conda`):

<details>

```yaml
# daskenv.yaml
name: daskenv
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- bokeh=0.12.4=py27_0
- boto3=1.4.4=py27_0
- conda-forge::appnope=0.1.0=py27_0
- conda-forge::backports.lzma=0.0.8=py27_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py27_1
- conda-forge::backports_abc=0.5=py27_0
- conda-forge::blas=1.1=openblas
- conda-forge::botocore=1.5.26=py27_0
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::certifi=2017.1.23=py27_0
- conda-forge::click=6.7=py27_0
- conda-forge::cloudpickle=0.2.2=py27_2
- conda-forge::decorator=4.0.11=py27_0
- conda-forge::distributed=1.16.0=py27_0
- conda-forge::docutils=0.13.1=py27_0
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::freetype=2.7=1
- conda-forge::futures=3.0.5=py27_0
- conda-forge::graphviz=2.38.0=4
- conda-forge::heapdict=1.0.0=py27_0
- conda-forge::ipython=5.3.0=py27_0
- conda-forge::ipython_genutils=0.2.0=py27_0
- conda-forge::jinja2=2.9.5=py27_0
- conda-forge::jmespath=0.9.2=py27_0
- conda-forge::jpeg=9b=0
- conda-forge::libgfortran=3.0.0=0
- conda-forge::libpng=1.6.28=0
- conda-forge::libtiff=4.0.6=7
- conda-forge::locket=0.2.0=py27_1
- conda-forge::markupsafe=0.23=py27_1
- conda-forge::msgpack-python=0.4.8=py27_0
- conda-forge::ncurses=5.9=10
- conda-forge::numpy=1.12.1=py27_blas_openblas_200
- conda-forge::openblas=0.2.19=1
- conda-forge::openssl=1.0.2h=3
- conda-forge::pandas=0.19.2=np112py27_1
- conda-forge::partd=0.3.7=py27_0
- conda-forge::pathlib2=2.2.1=py27_0
- conda-forge::pexpect=4.2.1=py27_0
- conda-forge::pickleshare=0.7.3=py27_0
- conda-forge::pip=9.0.1=py27_0
- conda-forge::prompt_toolkit=1.0.13=py27_0
- conda-forge::psutil=5.2.0=py27_0
- conda-forge::ptyprocess=0.5.1=py27_0
- conda-forge::py=1.4.33=py27_0
- conda-forge::pyfftw=0.10.4=np112py27_1
- conda-forge::pygments=2.2.0=py27_0
- conda-forge::pytest=3.0.7=py27_0
- conda-forge::python=2.7.13=0
- conda-forge::python-dateutil=2.6.0=py27_0
- conda-forge::python-graphviz=0.6=py27_0
- conda-forge::pytz=2016.10=py27_0
- conda-forge::pyyaml=3.12=py27_0
- conda-forge::readline=6.2=0
- conda-forge::requests=2.13.0=py27_0
- conda-forge::s3fs=0.0.9=py27_0
- conda-forge::s3transfer=0.1.10=py27_0
- conda-forge::scandir=1.5=py27_1
- conda-forge::scipy=0.19.0=np112py27_blas_openblas_200
- conda-forge::setuptools=33.1.1=py27_0
- conda-forge::simplegeneric=0.8.1=py27_0
- conda-forge::singledispatch=3.4.0.3=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::sortedcontainers=1.5.3=py27_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::ssl_match_hostname=3.5.0.1=py27_1
- conda-forge::tk=8.5.19=1
- conda-forge::toolz=0.8.2=py27_0
- conda-forge::tornado=4.4.2=py27_0
- conda-forge::traitlets=4.3.2=py27_0
- conda-forge::wcwidth=0.1.7=py27_0
- conda-forge::wheel=0.29.0=py27_0
- conda-forge::xz=5.2.2=0
- conda-forge::yaml=0.1.6=0
- conda-forge::zict=0.1.1=py27_0
- conda-forge::zlib=1.2.11=0
- tblib=1.3.0=py27_0
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - dask (/Users/kirkhamj/Developer/PyCharmCE/dask)==0.14.0+62.gd6c3443
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.13
prefix: /zopt/conda2/envs/daskenv
```

</details>
