### ISSUE TITLE
NumPy rfft2/rfftn return original shape with repeated axes

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#8855]
Normally NumPy's `rfft2`/`rfftn` returns an array whose shape is largely the same as that of the input (as long as `s` is unspecified) with one exception. Namely the last axis in `axes` will specify the dimension whose length will be reduced by `l // 2 + 1`, where `l` was the original length of that dimension. This is even noted in the docs. However, it seems if the last axis is repeated this no longer holds. Now I could be wrong, but this is not what I would naively expect. If this does make sense for some reason, then the docs probably should be updated.

<details>

```python
In [1]: import numpy

In [2]: import numpy.fft

In [3]: a = numpy.random.random((6, 7, 8, 9))

In [4]: numpy.fft.rfft2(a, axes=(0,)).shape
Out[4]: (4, 7, 8, 9)

In [5]: numpy.fft.rfft2(a, axes=(0, 1)).shape
Out[5]: (6, 4, 8, 9)

In [6]: numpy.fft.rfft2(a, axes=(0, 0)).shape
Out[6]: (6, 7, 8, 9)

In [7]: numpy.fft.rfftn(a, axes=(0,)).shape
Out[7]: (4, 7, 8, 9)

In [8]: numpy.fft.rfftn(a, axes=(0, 1)).shape
Out[8]: (6, 4, 8, 9)

In [9]: numpy.fft.rfftn(a, axes=(0, 0)).shape
Out[9]: (6, 7, 8, 9)
```

</details>
<br>
Exported environment details from `conda`:
<br>
<br>
<details>

```yaml
name: npenv
channels: !!python/tuple
- !!python/unicode
  'nanshe'
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'jakirkham'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::appnope=0.1.0=py27_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py27_1
- conda-forge::blas=1.1=openblas
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::certifi=2017.1.23=py27_0
- conda-forge::decorator=4.0.11=py27_0
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::ipython=5.3.0=py27_0
- conda-forge::ipython_genutils=0.2.0=py27_0
- conda-forge::libgfortran=3.0.0=0
- conda-forge::ncurses=5.9=10
- conda-forge::numpy=1.12.1=py27_blas_openblas_200
- conda-forge::openblas=0.2.19=1
- conda-forge::openssl=1.0.2h=3
- conda-forge::pathlib2=2.2.1=py27_0
- conda-forge::pexpect=4.2.1=py27_0
- conda-forge::pickleshare=0.7.3=py27_0
- conda-forge::prompt_toolkit=1.0.13=py27_0
- conda-forge::ptyprocess=0.5.1=py27_0
- conda-forge::pygments=2.2.0=py27_0
- conda-forge::python=2.7.13=0
- conda-forge::readline=6.2=0
- conda-forge::scandir=1.5=py27_1
- conda-forge::setuptools=33.1.1=py27_0
- conda-forge::simplegeneric=0.8.1=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=1
- conda-forge::traitlets=4.3.2=py27_0
- conda-forge::wcwidth=0.1.7=py27_0
- conda-forge::zlib=1.2.11=0
```

</details>
<br>
ref: https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.fft.rfftn.html
