### ISSUE TITLE
Strange rull multiaxis behavior

### ISSUE THREAD

**Issue by jakirkham** [numpy/numpy#8875]
Noticed there is some strange behavior with `numpy.roll` when using multiple shifts and/or axes. Descriptions of the odd cases are given below and a Python snippet is provided to show this in more detail.

First it is possible to use multiple shifts when no `axis` is specified. The no `axis` case flattens the array, which makes specifying multiple shifts weird. It seems `numpy.roll` permits this without error and just sums the shifts. Especially as there is already a way to accomplish this, whose intent is completely clear unlike this. Seems like erroring out would be better behavior IMHO.

Second if a number of shifts and a single axis is specified, the shifts can be summed together and applied along that axis. Much like the previous case, this feels like an indirect/unclear way to accomplish something that is much simpler and clearer otherwise. Note if more than one axis is specified, but doesn't match the number of shifts, it actually errors out. Again IMHO an error seems appropriate for all of these cases.

Examples:

<details>

```python
In [1]: import numpy as np

In [2]: a = np.arange(24.0).reshape(1, 2, 3, 4)

In [3]: a
Out[3]: 
array([[[[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.]],

        [[ 12.,  13.,  14.,  15.],
         [ 16.,  17.,  18.,  19.],
         [ 20.,  21.,  22.,  23.]]]])

In [4]: np.roll(a, (2, 3))
Out[4]: 
array([[[[ 19.,  20.,  21.,  22.],
         [ 23.,   0.,   1.,   2.],
         [  3.,   4.,   5.,   6.]],

        [[  7.,   8.,   9.,  10.],
         [ 11.,  12.,  13.,  14.],
         [ 15.,  16.,  17.,  18.]]]])

In [5]: np.roll(a, 5)
Out[5]: 
array([[[[ 19.,  20.,  21.,  22.],
         [ 23.,   0.,   1.,   2.],
         [  3.,   4.,   5.,   6.]],

        [[  7.,   8.,   9.,  10.],
         [ 11.,  12.,  13.,  14.],
         [ 15.,  16.,  17.,  18.]]]])

In [6]: np.roll(a, (2, 3), (1,))
Out[6]: 
array([[[[ 12.,  13.,  14.,  15.],
         [ 16.,  17.,  18.,  19.],
         [ 20.,  21.,  22.,  23.]],

        [[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.]]]])

In [7]: np.roll(a, 5, 1)
Out[7]: 
array([[[[ 12.,  13.,  14.,  15.],
         [ 16.,  17.,  18.,  19.],
         [ 20.,  21.,  22.,  23.]],

        [[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.]]]])

In [8]: np.roll(a, (1, 2, 3), (0, 1))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-57b473084941> in <module>()
----> 1 np.roll(a, (1, 2, 3), (0, 1))

/zopt/conda2/envs/npenv/lib/python2.7/site-packages/numpy/core/numeric.pyc in roll(a, shift, axis)
   1461 
   1462     else:
-> 1463         broadcasted = broadcast(shift, axis)
   1464         if len(broadcasted.shape) > 1:
   1465             raise ValueError(

ValueError: shape mismatch: objects cannot be broadcast to a single shape
```

</details>

<br>
Environment details:
<br>
<br>

<details>

```yaml
name: npenv
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::appnope=0.1.0=py27_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py27_1
- conda-forge::blas=1.1=openblas
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::certifi=2017.1.23=py27_0
- conda-forge::decorator=4.0.11=py27_0
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::ipython=5.3.0=py27_0
- conda-forge::ipython_genutils=0.2.0=py27_0
- conda-forge::libgfortran=3.0.0=0
- conda-forge::ncurses=5.9=10
- conda-forge::numpy=1.12.1=py27_blas_openblas_200
- conda-forge::openblas=0.2.19=1
- conda-forge::openssl=1.0.2h=3
- conda-forge::pathlib2=2.2.1=py27_0
- conda-forge::pexpect=4.2.1=py27_0
- conda-forge::pickleshare=0.7.3=py27_0
- conda-forge::prompt_toolkit=1.0.14=py27_0
- conda-forge::ptyprocess=0.5.1=py27_0
- conda-forge::pygments=2.2.0=py27_0
- conda-forge::python=2.7.13=0
- conda-forge::readline=6.2=0
- conda-forge::scandir=1.5=py27_1
- conda-forge::setuptools=33.1.1=py27_0
- conda-forge::simplegeneric=0.8.1=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=1
- conda-forge::traitlets=4.3.2=py27_0
- conda-forge::wcwidth=0.1.7=py27_0
- conda-forge::zlib=1.2.11=0
prefix: /zopt/conda2/envs/npenv
```

</details>
